# Generated by Django 3.2.7 on 2021-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
